-- MySQL Script generated by MySQL Workbench
-- Fri Jun  3 00:00:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laca_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laca_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `laca_db` ;

-- -----------------------------------------------------
-- Table `laca_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`categories` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laca_db`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`packages` (
  `id` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laca_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` DECIMAL(5,2) NULL DEFAULT NULL,
  `package_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `stock` DECIMAL(5,0) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_package_idx` (`package_id` ASC) VISIBLE,
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `laca_db`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_package`
    FOREIGN KEY (`package_id`)
    REFERENCES `laca_db`.`packages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laca_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`users` (
  `id` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dni` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `genero` TINYINT(1) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laca_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`cart` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `quantity` DECIMAL(5,0) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_userid_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_productid_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_userid2_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_productid2`
    FOREIGN KEY (`product_id`)
    REFERENCES `laca_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userid2`
    FOREIGN KEY (`user_id`)
    REFERENCES `laca_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laca_db`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laca_db`.`publications` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `description` TEXT NOT NULL,
  `price` FLOAT NOT NULL,
  `quantity` DECIMAL(5,0) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productid_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_userid_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_productid`
    FOREIGN KEY (`product_id`)
    REFERENCES `laca_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `laca_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
